// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebnzvhwtnjukufrlsgei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVibnp2aHd0bmp1a3VmcmxzZ2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTA4NzEsImV4cCI6MjA2Nzk4Njg3MX0.-LEdCX4GLpKUXC5SfduhulFl0l7H4CSD9R2113lHme4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});